# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build job'
    steps:
    - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'
- stage: 'ArchiveArtifacts'
  jobs:
  - job: 'Archive Job'
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'Build/*.jar'
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
        replaceExistingArchive: true 
- stage: 'Publish to Container'
  jobs:
  - job: 'Copy archived artifacts'
    steps:
    - taks: AzureFileCopy@3
      inputs:
        sourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        azureSubscription: 
        destination: azureBlob
        #azureSubscription: '83240f0b-c5c5-48a0-a2a9-c64cae45698f'
        azureSubscription: 'nav-pipeline-dev'
        storage: 'azurepocstorageforgradle'
        ContainerName: 'azurepocscontainerforgradle'
        #outputStorageUri: 'https://radoslaw.cisz@tomtom.com.blob.core.windows.net'
        #outputStorageUri: 'https://azurepocstorageforgradle.blob.core.windows.net/azurepocscontainerforgradle?sp=racwdl&st=2020-01-17T12:41:29Z&se=2020-01-18T12:41:29Z&sv=2019-02-02&sr=c&sig=QwQjLuv04c0CiqyChDvIQXwCgloMZzNQ63C14yvMufc%3D'
        #outputStorageContainerSasToken: Parameters.outputStorageContainerSasToken        
        #?sp=racwdl&st=2020-01-17T12:41:29Z&se=2020-01-18T12:41:29Z&sv=2019-02-02&sr=c&sig=QwQjLuv04c0CiqyChDvIQXwCgloMZzNQ63C14yvMufc%3D
        #sasTokenTimeOutInMinutes: 5