trigger:
- stashArtifacts
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Build'
  jobs:
  - job: BuildJob
    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build'    
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/build
        artifact: gradleBuild    
- stage: ArchiveArtifacts
  jobs:
  - job: 'ArchiveJob'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: gradleBuild
        patterns: '**/*.jar'
    - script: 'echo "Pipeline.Workspace = $(Pipeline.Workspace)" ; ls -al $(Pipeline.Workspace)'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)/libs'
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    - task: AzureFileCopy@3
      inputs:
        sourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'      
        Destination: 'AzureBlob'
        azureSubscription: 'rcAzureRMConnection'
        storage: 'azurepocstorageforgradle'
        ContainerName: 'azurepocscontainerforgradle'
        #outputStorageUri: 'https://radoslaw.cisz@tomtom.com.blob.core.windows.net'
        #outputStorageUri: 'https://azurepocstorageforgradle.blob.core.windows.net/azurepocscontainerforgradle?sp=racwdl&st=2020-01-17T12:41:29Z&se=2020-01-18T12:41:29Z&sv=2019-02-02&sr=c&sig=QwQjLuv04c0CiqyChDvIQXwCgloMZzNQ63C14yvMufc%3D'
        #outputStorageContainerSasToken: Parameters.outputStorageContainerSasToken        
        #?sp=racwdl&st=2020-01-17T12:41:29Z&se=2020-01-18T12:41:29Z&sv=2019-02-02&sr=c&sig=QwQjLuv04c0CiqyChDvIQXwCgloMZzNQ63C14yvMufc%3D
        #sasTokenTimeOutInMinutes: 5

