trigger:
- test
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Build'
  jobs:
  - job: BuildJob
    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build'
    #- script: 'sudo apt-get update ; sudo apt-get -y install tree ; tree'
    - script: 'touch $(System.DefaultWorkingDirectory)/file_DefaultWorkingDirectory'
    - script: 'echo "System.DefaultWorkingDirectory = $(System.DefaultWorkingDirectory)" ; ls -al $(System.DefaultWorkingDirectory)'
    - script: 'touch $(Build.BinariesDirectory)/file_BinariesDirectory'
    - script: 'echo "Build.BinariesDirectory = $(Build.BinariesDirectory)" ; ls -al $(Build.BinariesDirectory)'
    - script: 'touch $(Agent.BuildDirectory)/file_AgentBuildDirectory'
    - script: 'echo "Agent.BuildDirectory = $(Agent.BuildDirectory)" ; ls -al $(Agent.BuildDirectory)'
- stage: ArchiveArtifacts
  jobs:
  - job: 'ArchiveJob'
    steps:
    - script: 'echo "System.DefaultWorkingDirectory = $(System.DefaultWorkingDirectory)" ; ls -al $(System.DefaultWorkingDirectory)'
    - script: 'echo "Build.BinariesDirectory = $(Build.BinariesDirectory)" ; ls -al $(Build.BinariesDirectory)'
    - script: 'echo "Agent.BuildDirectory = $(Agent.BuildDirectory)" ; ls -al $(Agent.BuildDirectory)'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
