trigger:
- test
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Build'
  jobs:
  - job: BuildJob
    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build'
    #- script: 'sudo apt-get update ; sudo apt-get -y install tree ; tree'
    - script: 'echo $(System.DefaultWorkingDirectory) ; echo $(Build.BinariesDirectory)'
    - script: 'ls -la $(System.DefaultWorkingDirectory) ; ls -la $(Build.BinariesDirectory)'
- stage: ArchiveArtifacts
  jobs:
  - job: 'ArchiveJob'
    steps:
    - script: 'echo $(System.DefaultWorkingDirectory) ; echo $(Build.BinariesDirectory)'
    - script: 'ls -la $(System.DefaultWorkingDirectory) ; ls -la $(Build.BinariesDirectory)'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
